name: .NET

on:
  push:
    branches:  
    - master
    - develop
  pull_request:
    branches:  
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        cd TH
        dotnet restore
    - name: Build
      run: |
        cd TH
        dotnet build --no-restore
    - name: Test
      run: |
        cd TH
        dotnet test --no-build --verbosity normal
